from lib.key_generation import KeyGeneration
from lib.pairwiseLocalAlignment import FeatureSelection
from lib.vectFromLocalFeatures import Vectorization
from lib.feature_map_csr_matrix import VectorizationNoFS
from lib.feature_selection_pca import VectorizationFSPCA
from lib.jacOnlyFromVect_wu import JaccardCoefficient
from lib.visualize import Visualize
from lib.visualize_MDS import MDS